### ISSUE TITLE
请问 ecdsa.Sign 和sm2.Sign 的区别

### ISSUE THREAD

**Issue by asdfsx** [emmansun/gmsm#105]
你好，最近在使用sm2 进行签名的时候遇到了以下的错误
```
Error:          Received unexpected error:
                   input overflows the modulus
```
报错的代码是`r, s, err = sm2.Sign(rand.Reader, &sk, data)`。检查后发现，sm2 会对密钥中的变量`D`与曲线的参数`N`进行比较，`D > N`时会报这个错误。
但是这段代码替换成golang自带的`ecdsa.Sign`是可以使用的。
想知道`sm2`、`ecdsa` 在签名的实现上有啥区别吗？

**Comment by emmansun** [comment]
sm2和ecdsa签名算法是不一样的，不过私钥值本来就是要求比参数N小的啊。你可以share一下你的私钥和较完整的代码吗？

**Comment by asdfsx** [comment]
找到问题了，与SM2库没有关系，是其他部分的业务代码由一个对私钥拆分合并的操作。拆分以后的内容有问题，导致合并后的结果超过了N。ecdsa因为没有对合并后的结果做校验所以没有问题，但是到sm2这里就出问题了。
