### ISSUE TITLE
Cannot build with go 1.21 (link: duplicated definition)

### ISSUE THREAD

**Issue by timonwong** [emmansun/gmsm#150]
link: duplicated definition of symbol addMulVVWx, from github.com/emmansun/gmsm/internal/bigmod and crypto/internal/bigmod

**Comment by emmansun** [comment]
影响非amd64平台

**Comment by emmansun** [comment]
published in v0.19.3

**Comment by timonwong** [comment]
Confirmed it's working now, thanks!
