### ISSUE TITLE
Builds have been temporarily disabled for private and public repositories due to a negative credit balance.

### ISSUE THREAD

**Issue by emmansun** [emmansun/gmsm#17]
Builds have been temporarily disabled for private and public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance.

**Comment by emmansun** [comment]
Create one github.com workflow action

**Comment by emmansun** [comment]
No ARM64 env. now

**Comment by xuyang2** [comment]
travis-ci.com 上的 ARM64 对开源项目好像还是免费的

- https://blog.travis-ci.com/2021-05-07-orgshutdown
- https://docs.travis-ci.com/user/billing-overview/#usage---credits

**Comment by emmansun** [comment]
travis ci初始额度用完后，开源项目要单独写邮件申请，看别人反馈，似乎很难通过。

**Comment by emmansun** [comment]
travis ci初始额度用完后，开源项目要单独申请，看别人反馈，似乎很难通过。

**Comment by emmansun** [comment]
申请被拒
![image](https://user-images.githubusercontent.com/7235232/150930657-4764f580-cd7b-4fce-aa6e-55bd838e0430.png)

**Comment by emmansun** [comment]
经过反复沟通，又获得了25k 一次性credits, 省着点用， 感谢Travis CI对OSS的支持！

![image](https://user-images.githubusercontent.com/7235232/151084508-98b6baaf-3c3e-4773-aaac-103627a360a6.png)
