### ISSUE TITLE
sm2 自定义密钥加密解密问题

### ISSUE THREAD

**Issue by r1is** [emmansun/gmsm#183]
假设公钥是：04438d85d65d9a4b7082d2f2714ea0753cf7726262e377b9e97fcbead40b8882630834a682ad6c5e0907333aff7db446e54aa4a0a12a3993d53c758947ccd14eff
私钥是：4e85afbc996fdc67b4f05880bd9c0d037932649215ae10cf7085720b6571054c
问题1:
请问如何对 “hello world” 进行SM2 公钥加密。
问题：2
请问对"5EE0E5D18118C3CE85B8E7E25EF128E5A744CFF45D01A045114BB47C38BB5075F6AC6A885382C601882F5430FE10F7D11394511A93D86CFFCD1F39A0F30E803618672BE57E5F0763DEE53179C80C6DE4D5579B7C2048F061E3810AADF15850DF6C7FBF8EFD7536E554DA4A" 进行解密。
密钥对来源：https://www.zytool.cn/util/SMUtil
希望能得到大佬的解答

**Comment by emmansun** [comment]
1. 如何生成私钥 https://pkg.go.dev/github.com/emmansun/gmsm@v0.23.0/sm2。
2. 这个网站https://www.zytool.cn/util/SMUtil 的加密结果C1不符合规范，C1是曲线点，用不压缩的方式的话，首字符应该是04，补上就可以解密了。
3. 如何加密，也请参考 https://pkg.go.dev/github.com/emmansun/gmsm@v0.23.0/sm2 相应的Encrypt / EncryptASN1方法。

```go
func TestZyTool(t *testing.T) {
	cipherBytes, _ := hex.DecodeString("045EE0E5D18118C3CE85B8E7E25EF128E5A744CFF45D01A045114BB47C38BB5075F6AC6A885382C601882F5430FE10F7D11394511A93D86CFFCD1F39A0F30E803618672BE57E5F0763DEE53179C80C6DE4D5579B7C2048F061E3810AADF15850DF6C7FBF8EFD7536E554DA4A")
	bytes, _ := hex.DecodeString("4e85afbc996fdc67b4f05880bd9c0d037932649215ae10cf7085720b6571054c")
	d := new(big.Int).SetBytes(bytes)
	// Create private key from *big.Int
	priv := new(PrivateKey)
	priv.Curve = P256()
	priv.D = d
	priv.PublicKey.X, priv.PublicKey.Y = priv.ScalarBaseMult(priv.D.Bytes())
	plaintext, err := priv.Decrypt(rand.Reader, cipherBytes, nil)
	if err != nil {
		t.Fatal(err)
	}
	if string(plaintext) != "hello world" {
		t.Errorf("expected hello world, got %v", string(plaintext))		
	}
}
```
