### ISSUE TITLE
这个库还是很专业的，可否提供一些常用的范例，方便用户参考使用？

### ISSUE THREAD

**Issue by it512** [emmansun/gmsm#186]

**Comment by emmansun** [comment]
这个软件设计开发的时候，已经尽量保持与go语言本身的crypto包保持兼容，尤其是cipher/sm2/sm3/sm4，所以基本用法也与go语言的密码模块类似。另外，本文件的文档https://godoc.org/github.com/emmansun/gmsm 里面，基本上每个包都有examples。所以，大多数基本用法应该是不成问题的。如果国内用户访问不到这个文档链接，可以考虑再搞一个。

**Comment by emmansun** [comment]
https://emmansun.github.io/gmsm , 目前添加了《SM2椭圆曲线公钥密码算法应用指南》，相信能够满足大部分需求了。

**Comment by it512** [comment]
谢谢，已经满足需求了
另外，建议大佬考虑一下loong64架构优化， 这个是国产cpu，很多项目都有信创要求，另外这个cpu 也很不错，也是主流架构，同时也是未来一段时间我国cpu 架构没有之一的选择。 请考虑支持，谢谢！

**Comment by it512** [comment]
谢谢，不过现在loong64已经今非昔比了， 大佬有空可以去了解一下目前loong64在各个分类的进度，例如linux内核， 编程语言支持如golang ， .net等
