### ISSUE TITLE
travis-ci badge url 404

### ISSUE THREAD

**Issue by xuyang2** [emmansun/gmsm#19]
https://travis-ci.com/emmansun/gmsm
=> redirect https://www.travis-ci.com/emmansun/gmsm
=> Page not found 

似乎应更新为 `[![Build Status](https://app.travis-ci.com/emmansun/gmsm.svg?branch=main)](https://app.travis-ci.com/emmansun/gmsm)`

![image](https://user-images.githubusercontent.com/6643001/151098731-f30912d8-a76e-431b-b13b-495c7a6500f5.png)

![image](https://user-images.githubusercontent.com/6643001/151098606-bf1a46d8-26ac-40e5-b419-44449795312b.png)

**Comment by emmansun** [comment]
是的，为了避免浪费一次Travis CI build，先禁止build，再修改。

**Comment by emmansun** [comment]
Thx!
