### ISSUE TITLE
SM9 加密验证部分好像有问题

### ISSUE THREAD

**Issue by deatil** [emmansun/gmsm#193]
根据 gmssl 的来看 https://github.com/guanzhi/GmSSL/blob/master/src/sm9_lib.c#L373 ，是用的 HmacSM3 签名，而不是 SM3 签名

**Comment by emmansun** [comment]
和#158 重复，你可以参考标准文档。

**Comment by emmansun** [comment]
你也可以看```TestEncryptSM9Sample```和标准附录示例对比。

**Comment by deatil** [comment]
> 你也可以看`TestEncryptSM9Sample`和标准附录示例对比。

文档里的是 sm3。不过里面也有说得看具体的实现，感觉就是这个需要可配置来选择，而不是默认

**Comment by emmansun** [comment]
> > 你也可以看`TestEncryptSM9Sample`和标准附录示例对比。
> 
> 文档里的是 sm3。不过里面也有说得看具体的实现，感觉就是这个需要可配置来选择，而不是固定是某一个

不知道你“得看具体的实现”源自标准的哪一部分。标准中对消息认证码函数的说明没有歧义。
![image](https://github.com/emmansun/gmsm/assets/7235232/b3d99879-abb1-4b1c-b588-42e7f39d0e51)

![image](https://github.com/emmansun/gmsm/assets/7235232/00f63a06-f74a-40ac-bed5-a78bd151ca86)
