### ISSUE TITLE
希望能做更多的封装，让使用更方便一些。减少手工padding、创建cipher对象等重复工作。

### ISSUE THREAD

**Issue by MaoJianwei** [emmansun/gmsm#195]
你好，这是个很棒的库！

希望能做更多的封装，让使用更方便一些。
类似tjfoc/gmsm这个库里面的[sm4.Sm4Cbc](https://github.com/MaoJianwei/gmsm/blob/5ef14fd0870a58704bcdd8903e0d30146dea1d41/sm4/sm4.go#L301)等全局工具函数，一次调用就可以完成加密，减少手工padding、创建cipher对象等重复工作：）

**Comment by emmansun** [comment]
首先感谢你的建议。我从以下几个方面解释一下：
* 本库的定位和职责，在于常用商用密码算法的实现和优化。譬如sm4 package，它就和Go语言中的aes package类似，实现特定的```cipher.Block```。
* 通常的对称加解密，无非就是创建```cipher.Block```，再创建具体的工作模式。有些加密模式需要对明文数据做一些处理。其实也并不复杂。
* 全局工具函数看似给调用者提供了便利，但也有缺点：调用者失去控制权，不够灵活，无状态、一次性。
* 如果确需那种全局工具函数，可以自己按需写一个，或者找一下类似的工具包。
