### ISSUE TITLE
SM9测试用例数据来源

### ISSUE THREAD

**Issue by Azzzting** [emmansun/gmsm#215]
您好，请问这一部分的数据来源是哪里？在ANS.1中并没有找到，标准中也没有。
<img width="803" alt="image" src="https://github.com/emmansun/gmsm/assets/138744150/d266642c-d0f0-4886-8f67-fad5755d98a8">

**Comment by emmansun** [comment]
这个是示例应用，标准中的测试数据请参考```sm9_test.go```。

**Comment by Azzzting** [comment]
感谢.
