### ISSUE TITLE
中金版本支持

### ISSUE THREAD

**Issue by Nightlan** [emmansun/gmsm#225]
目前只支持了中金的SM2私钥、证书封装处理，后续会实现中金版本的签名，加密版本吗

**Comment by emmansun** [comment]
中金有自己的签名和加密版本？有文档吗？

**Comment by Nightlan** [comment]
我用这个库和java版本的cfca库做签名对比，发现结果不一样，看了下源码，似乎是在用sm3做摘要的，计算hash的时候，填充模式不一样？中金是基于一个叫BCSoftLib的库做的

**Comment by emmansun** [comment]
> 我用这个库和java版本的cfca库做签名对比，发现结果不一样，看了下源码，似乎是在用sm3做摘要的，计算hash的时候，填充模式不一样？中金是基于一个叫BCSoftLib的库做的

你要区分什么不一样。结果不一样是r s最终序列化输出格式不一样还是其它什么不一样。r s值不一样是肯定的，同样的消息，签名结果就是不一样的。互操作性是指你生成的签名，我能验签；反过来我生成的签名，你能验签。只要都是按标准实现的，互操作性应该不成问题。

**Comment by emmansun** [comment]
而且，SM2签名时，通常直接传入待签名数据，而不是hash，你可以看我的那个SM2应用指南。

**Comment by Nightlan** [comment]
好的，我这边刚接触国密，正在接入一个银行的sdk，他提供了一个demo是java版本的，我看是cfca提供的库，我这边想用golang来做对接
也就是说cfca只有证书和私钥的格式标准是特殊的，其他的加密和签名标准没有做特殊处理是吗，我直接用这个库就行了吗

**Comment by emmansun** [comment]
> 好的，我这边刚接触国密，正在接入一个银行的sdk，他提供了一个demo是java版本的，我看是cfca提供的库，我这边想用golang来做对接 也就是说cfca只有证书和私钥的格式标准是特殊的，其他的加密和签名标准没有做特殊处理是吗，我直接用这个库就行了吗

对的

**Comment by Nightlan** [comment]
你好，签名这里应该是没有问题，不过加密这里中金应该是采用数字信封的实现吧？我看java源码走了一次sm4的加密

**Comment by Nightlan** [comment]
中金应该采用的是数字信封机制，走sm4的CBC模式做的对称加密

**Comment by emmansun** [comment]
这是具体应用场景、模式吧，和标准没有关系。如果需要帮助，你可以贴出JAVA实现。关于SM4，你可以参考https://emmansun.github.io/gmsm/docs/sm4.html

**Comment by Nightlan** [comment]
![image](https://github.com/emmansun/gmsm/assets/23734656/9fc53083-98f5-4297-bdf1-127073342120)
这个是cfca sm2加密的实现代码部分截图

**Comment by Nightlan** [comment]
我看他用的是sm4加密，但是sm4的加密参数里，用到了公钥做初始化，不太确定他这个到底是怎么实现的，我如何用golang实现这个效果

**Comment by Nightlan** [comment]
![image](https://github.com/emmansun/gmsm/assets/23734656/486ba72e-6b82-4fd3-8ac5-b132ea9871c9)
这个应该是sm4加密参数的初始化代码

**Comment by emmansun** [comment]
你参考https://github.com/emmansun/gmsm/blob/main/pkcs7/encrypt_test.go 和相关的解密。

**Comment by Nightlan** [comment]
![image](https://github.com/emmansun/gmsm/assets/23734656/0b70dd9c-0635-42f9-b878-7fb86a2e54a2)
我用了这个参数加密并base64后，然后使用中金的sdk解析，还是报错了，不过看起来加密流程好像是对的，提示非法的指针
![image](https://github.com/emmansun/gmsm/assets/23734656/85cf4ec1-80ba-438c-986c-4d71c71bac74)

**Comment by Nightlan** [comment]
![image](https://github.com/emmansun/gmsm/assets/23734656/2760199c-1b22-497c-a91b-1cd37ceb5a33)

**Comment by Nightlan** [comment]
这个ecpoint报出来的

**Comment by emmansun** [comment]
以及那个checkRecioientsAndSymmetricKey方法。

**Comment by Nightlan** [comment]
![image](https://github.com/emmansun/gmsm/assets/23734656/9efe360c-575d-4ea7-a0b8-863f99431798)

**Comment by Nightlan** [comment]
![image](https://github.com/emmansun/gmsm/assets/23734656/c1e2c994-f997-4962-990d-a4d9665872c9)
buildRecipients是这里吗

**Comment by emmansun** [comment]
是envelopMessage方法中的，估计要追到session.encrypt和session.decrypt方法了

**Comment by Nightlan** [comment]
![image](https://github.com/emmansun/gmsm/assets/23734656/7a6eba3d-07ba-436d-bd56-4fccf01ea221)
这里吗，就是红框里面异常了

**Comment by Nightlan** [comment]
![image](https://github.com/emmansun/gmsm/assets/23734656/3aee06bd-b919-4069-a666-fa94bfb8589e)

**Comment by Nightlan** [comment]
![image](https://github.com/emmansun/gmsm/assets/23734656/1e79cd01-75db-4951-8305-947d09076fda)

**Comment by emmansun** [comment]
果然，CFCA还是用了老旧的C1C2C3密文格式。等我下周看看怎么在pkcs7实现里面支持这种老旧密文格式吧。

**Comment by Nightlan** [comment]
现在不支持是吗

**Comment by emmansun** [comment]
> 现在不支持是吗

单独的SM2加密是支持所有格式的，PKCS7不支持。

**Comment by Nightlan** [comment]
这个支持麻烦吗，我这边最近需要急用

**Comment by emmansun** [comment]
> 这个支持麻烦吗，我这边最近需要急用

你可以自己试着实现一下，就是加解密key的时候，密文改为cfca(底下bc库)支持的C1C2C3格式，其它流程一样。

**Comment by Nightlan** [comment]
![image](https://github.com/emmansun/gmsm/assets/23734656/fceaa810-b4cc-42a1-bea4-f645d328efac)主要是我之前没有很深入了解密码学这块的，尤其是国密，这个里面吗

**Comment by Nightlan** [comment]
CFCA的私钥、证书封装处理也是特定的吧，我之前就是用github.com/tjfoc/gmsm搞了半天，私钥文件解不开，发现俩边实现的不一致，就找到了你这个库

**Comment by emmansun** [comment]
你用的是SADK吗？**SADK-3.2.1.3**中sm2加解密的密文格式已经是ASN.1格式了
```java
  public byte[] encrypt(byte[] sourceData) {
    if (sourceData == null)
      throw new SecurityException("null/length not allowed for sourceData"); 
    try {
      byte[] data = (byte[])sourceData.clone();
      this.datSM3Engine.update(data, 0, data.length);
      for (int i = 0; i < data.length; i++) {
        if (this.keyOff == this.key.length)
          nextKey(); 
        this.keyOff = (byte)(this.keyOff + 1);
        data[i] = (byte)(data[i] ^ this.key[this.keyOff]);
      } 
      byte[] hashValue = new byte[32];
      dofinal(hashValue);
      ASN1SM2Cipher asn1 = new ASN1SM2Cipher(this.C1XCoord, this.C1YCoord, hashValue, data);
      return asn1.getEncoded("DER");
    } catch (IOException e) {
      throw new RuntimeException("encrypt failure", e);
    } 
  }
```

**Comment by Nightlan** [comment]
SADK是cfca提供的吗，我这边用的是银行提供的jar包和demo，看到它里面的包都是cfca的，不确定是不是SADK
![image](https://github.com/emmansun/gmsm/assets/23734656/a78491e2-8059-428e-9ad9-724baaf4d0c5)

**Comment by Nightlan** [comment]
我这边的验证方式是使用pkcs7.EncryptSM加密，然后用银行的解密函数看是否能解开，我看仓库有新的提交，可以用最新的tag试试吗

**Comment by emmansun** [comment]
你最好还是搞清楚先，CFCA用的还是就是SADK（Security Application Development Kit

- https://www.cfca.com.cn/20150807/101228565.html
- https://github.com/bubicn/bubichain-sdk-java/blob/master/jar/sadk-3.2.3.0.RELEASE.jar

**Comment by Nightlan** [comment]
我刚看了下，是的
![image](https://github.com/emmansun/gmsm/assets/23734656/793ea3b2-95dd-4ac9-b942-b5992ff59345)

**Comment by emmansun** [comment]
估计是比较老旧的版本，你试一下吧[v0.27.3-beta.0](https://github.com/emmansun/gmsm/releases/tag/v0.27.3-beta.0)

**Comment by Nightlan** [comment]
还是报错了
![image](https://github.com/emmansun/gmsm/assets/23734656/0ca9fa6a-f49e-4ab8-a998-ae686b31f8e5)

**Comment by Nightlan** [comment]
![image](https://github.com/emmansun/gmsm/assets/23734656/10e2eebb-fece-4383-ac21-9a557803509f)

**Comment by Nightlan** [comment]
![image](https://github.com/emmansun/gmsm/assets/23734656/64216ac9-b965-4430-933c-01e3b0c39682)
之前报错的地方通过了，现在是另外一个问题

**Comment by Nightlan** [comment]
他们这个版本之间是不兼容吗，不好搞的话，我还是考虑用java吧

**Comment by emmansun** [comment]
> 他们这个版本之间是不兼容吗，不好搞的话，我还是考虑用java吧

看起来SADK 3.1和3.2+之间是不兼容的，不过刚才那个错误是SADK一以贯之的，就是把SM4 OID当作 SM4 CBC OID.

**Comment by emmansun** [comment]
[v0.27.3-beta.1](https://github.com/emmansun/gmsm/releases/tag/v0.27.3-beta.1), 用EncryptCFCA，cipher用pkcs.SM4

**Comment by Nightlan** [comment]
厉害，现在可以解开了

**Comment by Nightlan** [comment]
非常感谢！

**Comment by Nightlan** [comment]
你好，打扰了，在这里额外请教一个java解密的问题，下面java的解密代码，golang有对应的实现吗
 PBEKeySpec keySpec = new PBEKeySpec(password);
            SecretKeyFactory keyFactory = SecretKeyFactory.getInstance("PBEWithSHAAndTwofish-CBC");
            SecretKey key = keyFactory.generateSecret(keySpec);
            PBEParameterSpec paramSpec = new PBEParameterSpec(salt, iterations);
            Cipher cipher = Cipher.getInstance("PBEWithSHAAndTwofish-CBC");
            cipher.init(2, key, paramSpec);
            PKCS8EncodedKeySpec spec = new PKCS8EncodedKeySpec(cipher.doFinal(remainingCipherData));
            KeyFactory factory = KeyFactory.getInstance(new String(algorithm));
            privatekey = factory.generatePrivate(spec);

**Comment by Nightlan** [comment]
在网上搜了下，golang好像没有看到PBEWithSHAAndTwofish的实现

**Comment by emmansun** [comment]
我看你是想处理SADK自定义的Keystore，我建议你还是用SADK读出想要的内容，存成其它语言能处理的格式。

**Comment by emmansun** [comment]
https://cs.opensource.google/go/x/crypto/+/master:pkcs12/crypto.go
https://cs.opensource.google/go/x/crypto/+/master:twofish/twofish.go

**Comment by Nightlan** [comment]
嗯，这俩个包我都用了，不知道是不是用法不对，通过调试对比，我这边生成的key和iv和java那边的不一样，下面是我写的golang版本，是哪里的参数传传错了，还是有少步骤呢

package main

import (
	"bytes"
	"crypto/cipher"
	"crypto/sha1"
	"crypto/x509"
	"encoding/base64"
	"fmt"
	"golang.org/x/crypto/pbkdf2"
	"golang.org/x/crypto/twofish"
	"os"
)

func decryptPrivateKey(encryptedPrivateKey []byte, password string) (interface{}, error) {
	iterations := 1000
	size := len(encryptedPrivateKey)
	salt := make([]byte, 1)
	reader := bytes.NewReader(encryptedPrivateKey)
	if _, err := reader.Read(salt); err != nil {
		return nil, err
	}
	l := salt[0]
	algorithm := make([]byte, l)
	if _, err := reader.Read(algorithm); err != nil {
		return nil, err
	}
	fmt.Println(string(algorithm))
	salt = make([]byte, 8)
	if _, err := reader.Read(salt); err != nil {
		return nil, err
	}
	remainingCipherData := make([]byte, size-8-1-int(l))
	if _, err := reader.Read(remainingCipherData); err != nil {
		return nil, err
	}
	key := pbkdf2.Key([]byte(password), salt, iterations, 32, sha1.New)

	block, err := twofish.NewCipher(key)
	if err != nil {
		return nil, err
	}

	if len(remainingCipherData)%twofish.BlockSize != 0 {
		return nil, err
	}
	iv := remainingCipherData[:twofish.BlockSize]
	remainingCipherData = remainingCipherData[twofish.BlockSize:]
	cbc := cipher.NewCBCDecrypter(block, iv)
	cbc.CryptBlocks(remainingCipherData, remainingCipherData)

	privateKey, err := x509.ParsePKCS8PrivateKey(remainingCipherData)
	if err != nil {
		return nil, err
	}

	return privateKey, nil
}

**Comment by Nightlan** [comment]
问题应该还是出在解密的那段，包括key和iv的生成这些

**Comment by Nightlan** [comment]
看了下，中信这套实现都是基于Bouncy Castle 这个java库弄的，golang没有对应实现，看来和银行打交道还是得用java，而且每个银行都有自己的标准

**Comment by emmansun** [comment]
**PBEWithSHAAndTwofish-CBC** GO语言参考实现https://gist.github.com/emmansun/29c319b30baa36eda0bf36b3d10169b0 。我先关掉这个议题了，有关本项目的问题，可以新开issue。
