### ISSUE TITLE
pkcs7签名算法和bouncycastle的CMSSignedDataGenerator差异问题

### ISSUE THREAD

**Issue by Nightlan** [emmansun/gmsm#227]
这个java的实现
![image](https://github.com/emmansun/gmsm/assets/23734656/9b25f8dc-89d5-4497-9ca0-460e2691fe28)
这个是我用的pkcs7的签名代码
![image](https://github.com/emmansun/gmsm/assets/23734656/485842a9-4764-41f8-8a24-b40fe308a4dd)

发现俩边签出来的不一样，是我的包用错了吗

**Comment by Nightlan** [comment]
pkcs7的这个函数是用来做签名的吗，我看返回的签名结果长度会变，java签名返回长度一直是固定的

**Comment by emmansun** [comment]
你可以用asn.1 在线工具比较一下，具体哪些不同。

**Comment by Nightlan** [comment]
结构应该是有差异的，pkcs7加密出来的解析结构：
<img width="1297" alt="image" src="https://github.com/emmansun/gmsm/assets/23734656/1bf6c08d-671b-424e-8bdd-3ade733c058a">
java的结构：
![image](https://github.com/emmansun/gmsm/assets/23734656/fda6ca92-342d-41b6-9fbc-7de40223b686)
看起来多了证书的信息吗，pkcs7的签名可以兼容java这个吗

**Comment by emmansun** [comment]
你是要对方可以verify，还是要结构一模一样？如果是对方可以验证，你直接测试一下就行；

如果结构一模一样，那你看看以谁为准，假如以java为准，那你看看golang多了什么：证书和签名数据，忽略证书的话，SignerInfoConfig有个配置选项，可以忽略证书；签名数据的话，调用Finish之前，先调用Detach。

**Comment by emmansun** [comment]
pkcs7项目只是部分实习了相关标准，测试也是主要和openssl进行，这里只是加了国密扩展。

**Comment by Nightlan** [comment]
我只要对方可以可以验签就行了

**Comment by Nightlan** [comment]
我只要使用java可以验签就行了

**Comment by Nightlan** [comment]
java的Detach传的是false

**Comment by emmansun** [comment]
> 我只要使用java可以验签就行了

https://www.baeldung.com/java-bouncy-castle

**Comment by Nightlan** [comment]
if err := toBeSigned.AddSignerChain(publicKey, privateKey, nil, pkcs7.SignerInfoConfig{
		SkipCertificates: true,
	})
	
	我设置这个后可以了

**Comment by emmansun** [comment]
> ```
> if err := toBeSigned.AddSignerChain(publicKey, privateKey, nil, pkcs7.SignerInfoConfig{
> 	SkipCertificates: true,
> })
> 
> 我设置这个后可以了
> ```

https://github.com/emmansun/pkcs7/pull/9

**Comment by Nightlan** [comment]
不过这个验签过程不需要使用到证书吗

**Comment by Nightlan** [comment]
有验签的完整代码吗，这个是java的，使用的传入证书验签
![image](https://github.com/emmansun/gmsm/assets/23734656/9da14369-4e70-4c03-9219-c3ff815fe101)

**Comment by emmansun** [comment]
> 有验签的完整代码吗，这个是java的，使用的传入证书验签 ![image](https://private-user-images.githubusercontent.com/23734656/340062533-9da14369-4e70-4c03-9219-c3ff815fe101.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MDg5MTksIm5iZiI6MTcxODUwODYxOSwicGF0aCI6Ii8yMzczNDY1Ni8zNDAwNjI1MzMtOWRhMTQzNjktNGU3MC00YzAzLTkyMTktYzNmZjgxNWZlMTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDAzMzAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMDJlZDhkZmQxY2I5NmJjMTA2Y2M4M2NhZDllZDhiY2NiN2Y5ZThhNTNkYjI5MmUzOTJlZmM1NmZjYjg1ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5vHuGcYAxVOpFuZykNCMwnLoUOQA0uptk95czh046RI)

对啊，如果签名数据不是自包含证书，那肯定要外部提供。不过当时那个PR只提交了支持生成不包含证书的SignedData，并没有提交Verify相应的适配，不知道是不是没有这样的需求。

**Comment by Nightlan** [comment]
嗯，那确实挺奇怪的，一般都要使用证书验签吧，golang的验签是这样写吗
![image](https://github.com/emmansun/gmsm/assets/23734656/06d17779-f8aa-4f1c-ab08-1a0e21201dee)

**Comment by emmansun** [comment]
BC不是支持标准的带证书的签名数据吗？为什么你们要这么做呢？

**Comment by Nightlan** [comment]
支持吗，我试了下把SkipCertificates设置为false，java那边就验签不通过了

**Comment by emmansun** [comment]
> 支持吗，我试了下把SkipCertificates设置为false，java那边就验签不通过了

可能你们的java实现比较特殊，自己生成的都不带，是不是特意这样做的。

**Comment by Nightlan** [comment]
java的实现是银行提供的demo，他的签名结果确实挺奇怪的
![image](https://github.com/emmansun/gmsm/assets/23734656/86dd556f-510e-40ee-983c-279108d7cdbf)
按理来说他传了证书，结果签出来的结果也没包含证书信息，调试发现Detach传的也是false，结果里也没有签名数据

**Comment by Nightlan** [comment]
验签的时候需要再传入公钥和加签内容，感觉他的验签也有点问题，别的私钥签的，也可以验签通过，不知道是不是只校验了格式

**Comment by Nightlan** [comment]
验签可以了，他需要在验签的时候把签名内容和证书再传进去

**Comment by emmansun** [comment]
> 验签可以了，他需要在验签的时候把签名内容和证书再传进去

1. 对Detach的验签，是先要给它原始待签名数据。
2. 对无证书的，要先给它提供签名者证书列表。

**Comment by Nightlan** [comment]
好的，问题解决了，感谢
