### ISSUE TITLE
使用openssl命令生成的SM2证书无法识别公钥算法

### ISSUE THREAD

**Issue by JackMingQiu** [emmansun/gmsm#236]
在使用smx509库时，解析openssl生成的sm2证书后，`Certificate.PublicKeyAlgorithm`识别为空，但是通过openssl指令可以识别出来。
我对比了一下smx509中test文件使用的sm2证书，和openssl生成的sm2证书，发现了在PublicKeyAlgorithm中二者的OID不同：
- openssl生成的sm2证书，公钥内容是：SEQUENCE {
283   8:         OBJECT IDENTIFIER sm2ECC (1 2 156 10197 1 301)
293   8:         OBJECT IDENTIFIER sm2ECC (1 2 156 10197 1 301)
       :         }

- test文件中的sm2证书，公钥内容是：SEQUENCE {
183   7:         OBJECT IDENTIFIER ecPublicKey (1 2 840 10045 2 1)
192   8:         OBJECT IDENTIFIER sm2ECC (1 2 156 10197 1 301)
       :         }

是否可以修正因为OID不同造成的识别不到的情况？

附上openssl所测试的pem证书：
```
-----BEGIN CERTIFICATE-----
MIICGzCCAcCgAwIBAgIUZ2YpsJJVNcwfjCHBEz8otQDEpUEwCgYIKoEcz1UBg3Uw
YjELMAkGA1UEBhMCSU4xEjAQBgNVBAgMCUJlbmdhbHVydTENMAsGA1UEBwwEQ2l0
eTEQMA4GA1UECgwHU29tZU9yZzENMAsGA1UECwwEVGVzdDEPMA0GA1UEAwwGUm9v
dENBMB4XDTI0MDgyNzAyMzQ1NloXDTM0MDgyNTAyMzQ1NlowYjELMAkGA1UEBhMC
SU4xEjAQBgNVBAgMCUJlbmdhbHVydTENMAsGA1UEBwwEQ2l0eTEQMA4GA1UECgwH
U29tZU9yZzENMAsGA1UECwwEVGVzdDEPMA0GA1UEAwwGUm9vdENBMFowFAYIKoEc
z1UBgi0GCCqBHM9VAYItA0IABC8HaH8+WYCtUk06wAFfzR09nnOlQOJ2oORwD25m
S55CdJv+Svzji0nSeSWtXBzo9y4Q6EKLDpOSQbKYeswVDoejUzBRMB0GA1UdDgQW
BBRSGm5/62dcOw8vkiG8YGoZMf6UIzAfBgNVHSMEGDAWgBRSGm5/62dcOw8vkiG8
YGoZMf6UIzAPBgNVHRMBAf8EBTADAQH/MAoGCCqBHM9VAYN1A0kAMEYCIQDC4s3P
wAKTEz+410/odAO30Wzam895L31T1MQ0EaBYtQIhALbw1l4lcun4RTVWYQN5A2r2
Cm2A1bCQaLWY1jsQTBpf
-----END CERTIFICATE-----
```

**Comment by emmansun** [comment]
请参考 https://github.com/emmansun/gmsm/issues/197

**Comment by JackMingQiu** [comment]
已解决，原来是openssl在3.2.1版本之后公钥的OID格式变成ec,sm2了，而我使用的是3.0版本，更新openssl之后就没问题了，谢谢作者快速准确的回应
