### ISSUE TITLE
[X509] simplify ParsePKIXPublicKey

### ISSUE THREAD

**Issue by xuyang2** [emmansun/gmsm#24]
现在 `parsePublicKey()` 和 `namedCurveFromOID()` 已经支持了 `oidNamedCurveP256SM2`，
貌似 `ParsePKIXPublicKey()` 没必要再对 `oidNamedCurveP256SM2` 单独处理了。

是否可以简化一下，直接用标准库一样的方法体
见 https://github.com/easyops-cn/emmansun-gmsm/commit/40159e654241d31fb2a11ca3620ae3e4cc988297

可以的话我就提个PR

**Comment by emmansun** [comment]
没问题，本来单独处理也是为了少维护SDK的内部代码，既然相应实现已经都搬过来了，特殊处理也就不需要了。
