### ISSUE TITLE
[X509] sync upstream

### ISSUE THREAD

**Issue by xuyang2** [emmansun/gmsm#25]
这两处代码 是否可以跟上游同步一下：

- https://github.com/golang/go/commit/1eeaff75f9e02c65d29d9910c1884c6c0ecc1430#diff-a789286d7e257f148c437404f8cf5d3379688597381ff13352e62ac406be295aR1671
- https://github.com/golang/go/commit/39eb1cc3f4a7d620d3faae139f83e88e652f5d25#diff-809b575e21dd0fe0fb11f755c955cea4b62a7581bfdab36b2993c02078077f27

**Comment by emmansun** [comment]
第一个“crypto/x509: enforce SAN IA5String encoding restrictions”，应该改一下isIA5String方法就行
第二个的话“crypto/x509: drop compatibility hack for expired COMODO intermediates”，先只改verify.go的checkChainForKeyUsage方法，删掉support COMODO certificate chains部分。
