### ISSUE TITLE
ink: duplicated definition of symbol addMulVVWx

### ISSUE THREAD

**Issue by zlog-fun** [emmansun/gmsm#259]
question：
link: duplicated definition of symbol addMulVVWx, from github.com/emmansun/gmsm/internal/bigmod and crypto/internal/bigmod

**Comment by emmansun** [comment]
What's you used version? it was fixed since [v0.19.3](https://github.com/emmansun/gmsm/releases/tag/v0.19.3)

**Comment by zlog-fun** [comment]
thinks. upgrade to v0.19.2.It's ok

**Comment by emmansun** [comment]
https://github.com/emmansun/gmsm/issues/150
