### ISSUE TITLE
cfca sadk 3.0.2.0

### ISSUE THREAD

**Issue by lnatpunblhna** [emmansun/gmsm#260]
大佬你好请教下 sadk 中 p7SignMessageAttach 对应的在go该如何实现？

**Comment by emmansun** [comment]
我没有sadk 3.0.2.0，不过看其它版本（3.2.3.0），应该是```pkcs7.SignWithoutAttr```。

**Comment by lnatpunblhna** [comment]
> 我没有sadk 3.0.2.0，不过看其它版本（3.2.3.0），应该是`pkcs7.SignWithoutAttr`。

我这边写了个demo测试了下 签出来和java有一点差别

**Comment by emmansun** [comment]
> > 我没有sadk 3.0.2.0，不过看其它版本（3.2.3.0），应该是`pkcs7.SignWithoutAttr`。
> 
> 我这边写了个demo测试了下 签出来和java有一点差别

差别具体指什么呢？

**Comment by lnatpunblhna** [comment]
> > > 我没有sadk 3.0.2.0，不过看其它版本（3.2.3.0），应该是`pkcs7.SignWithoutAttr`。
> > 
> > 
> > 我这边写了个demo测试了下 签出来和java有一点差别
> 
> 差别具体指什么呢？

go:
![7ba4d6eb-f1d9-4952-96d2-8556e25944bc](https://github.com/user-attachments/assets/b600622e-2feb-4d14-b88b-10b0ebd0c4a5)
java:
![83702c77-732c-4ee4-bc7d-f4c8bf9b7dfd](https://github.com/user-attachments/assets/93dcde16-312d-4b8b-8cb5-a1fb9d49294c)

目前看起来是签名中缺少可选参数导致的
![a92fe230-1d81-410e-90c5-61c3355bec6b](https://github.com/user-attachments/assets/71bee6cf-611c-4cfa-b30a-3975eaaa9afe)

**Comment by lnatpunblhna** [comment]
> > > > 我没有sadk 3.0.2.0，不过看其它版本（3.2.3.0），应该是`pkcs7.SignWithoutAttr`。
> > > 
> > > 
> > > 我这边写了个demo测试了下 签出来和java有一点差别
> > 
> > 
> > 差别具体指什么呢？
> 
> go: ![7ba4d6eb-f1d9-4952-96d2-8556e25944bc](https://private-user-images.githubusercontent.com/33893697/380106108-b600622e-2feb-4d14-b88b-10b0ebd0c4a5.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTA3NTQsIm5iZiI6MTcyOTg1MDQ1NCwicGF0aCI6Ii8zMzg5MzY5Ny8zODAxMDYxMDgtYjYwMDYyMmUtMmZlYi00ZDE0LWI4OGItMTBiMGViZDBjNGE1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMDAwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTkwNTkyMTQ4ZjI4NzM2MzdmNjI4ZmM3ODdhMWU2ODRiZDIwMzZjZGExYzJkMTVmMGZiMmU2OWU5NDVlZjM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GgR_5QgupWXXlvP9bkUn7wVW792w_YG64snxjO9vJRc) java: ![83702c77-732c-4ee4-bc7d-f4c8bf9b7dfd](https://private-user-images.githubusercontent.com/33893697/380106194-93dcde16-312d-4b8b-8cb5-a1fb9d49294c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTA3NTQsIm5iZiI6MTcyOTg1MDQ1NCwicGF0aCI6Ii8zMzg5MzY5Ny8zODAxMDYxOTQtOTNkY2RlMTYtMzEyZC00YjhiLThjYjUtYTFmYjlkNDkyOTRjLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMDAwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmM1ZmYxNGUyY2Q0MjZmZTJiOTYxMTk1NDk1NTZkODAxYTU5OWQ3MzBiYWU5MDRiNGEwYWMxYzllMGMyMWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RgsXku-KP2DYB-TtO3cBWxGa57DPfNrQsYzRSTqmsKE)
> 
> 目前看起来是签名中缺少可选参数导致的 ![a92fe230-1d81-410e-90c5-61c3355bec6b](https://private-user-images.githubusercontent.com/33893697/380106446-71bee6cf-611c-4cfa-b30a-3975eaaa9afe.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTA3NTQsIm5iZiI6MTcyOTg1MDQ1NCwicGF0aCI6Ii8zMzg5MzY5Ny8zODAxMDY0NDYtNzFiZWU2Y2YtNjExYy00Y2ZhLWIzMGEtMzk3NWVhYWE5YWZlLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMDAwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzY0MDU1NjRjNjg5N2E3YThlMzQwMTBlOTBiOGQzMTM5MTExYmQ4Y2M5MTkwOWJjZDVmZjkwMDIyZjg1ZDEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FhRmt2S3n3NlWdn-TeGUgpllTR61P6Kjie7g3ntkXh8)

添加自定义参数 tag:5

**Comment by emmansun** [comment]
就像你说的，Parameters本来就是optional的，这有什么影响呢？cfca 3.0.2.0的代码验证不了go生成的签名？还是反过来？3.2.3.0中就都是NULL啊。
![image](https://github.com/user-attachments/assets/5ed2e2df-764f-43c8-a99b-88fe1a0a4dc3)

**Comment by lnatpunblhna** [comment]
> 就像你说的，Parameters本来就是optional的，这有什么影响呢？cfca 3.0.2.0的代码验证不了go生成的签名？还是反过来？3.2.3.0中就都是NULL而已啊， tag=5就是DERNull。 ![image](https://private-user-images.githubusercontent.com/7235232/380113315-5ed2e2df-764f-43c8-a99b-88fe1a0a4dc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTE2NjIsIm5iZiI6MTcyOTg1MTM2MiwicGF0aCI6Ii83MjM1MjMyLzM4MDExMzMxNS01ZWQyZTJkZi03NjRmLTQzYzgtYTk5Yi04OGZlMWEwYTRkYzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjVUMTAxNjAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjIwZTZhMTRlZmQ0ZTUzZWUyN2FmY2ZkNWYyZWVjODc3Y2ZmZmM1YWU0YjAwMzZkZjViZjZmMDQ3MTZmNGE4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dV1D8t3J1Oirpn8OImX96eeHt43ZGvqv7OkFKzVRC1A)

测试了一下是可以的不好意思打扰了
