### ISSUE TITLE
大佬您好，请问sm4 cmac算法有提供吗

### ISSUE THREAD

**Issue by AManHasNoName12138** [emmansun/gmsm#268]

**Comment by emmansun** [comment]
CMAC 算法这里没有提供，你可以找一下其它实现，譬如[The CMAC/OMAC1 message authentication code](https://github.com/aead/cmac)，然后结合使用SM4应该就可以了。

**Comment by AManHasNoName12138** [comment]
好的，感谢大佬回复

**Comment by mei-rune** [comment]
这个我也有需要， 但完全不懂

**Comment by emmansun** [comment]
什么国密使用场景？

**Comment by mei-rune** [comment]
一个政府部门，要求用这个 来检查用户信息的完整性。他们叫 sm4 mac 不知和这个是不是同一个。

**Comment by emmansun** [comment]
CBC–MAC和CMAC是不同的，CBC–MAC就是取CBC加密的最后一个块作为MAC值，其安全性和CBC加密一样。两者都是用块加密来生成MAC值，性能取决于使用的块加密（AES/SM4），而且不能并行。两者使用都不广泛，消息鉴别码的话，目前用哈希（HMAC）的多一点，加密带认证码的话用GCM模式好一点。无脑强制性使用，那就硬着头皮上吧。

**Comment by mei-rune** [comment]
这个我们没有办法决定，客户指定，还要检察， 只能用它了， 我对加密完完不懂，只能问问你能不能添加一下支持。
