### ISSUE TITLE
Hello I want to use sm4 decrypt (SM4/ECB/PKCS5Padding), how to do that 

### ISSUE THREAD

**Issue by ninjachen** [emmansun/gmsm#278]
Hello I want to use sm4 decrypt (SM4/ECB/PKCS5Padding), how to do that? 
It was not mentioned in the Docs

**Comment by emmansun** [comment]
PKCS5Padding是遗留系统用于block size = 8字节时代的padding 模式，当用于block size = 16字节时，应该要用PKCS7Padding。当PKCS5Padding用于block size = 16字节时，其实现和PKCS7Padding结果通常一样。至于SM4/ECB/PKCS5Padding怎么用，也就成了SM4/ECB/PKCS7Padding怎么用，那其实其用法和SM4/CBC/PKCS7Padding类似。

**Comment by ninjachen** [comment]
谢谢解惑，我看到CBC的example是这样的, 是要找cipher.NewECBEncrypter吗？好像它不存在
```
mode := cipher.NewCBCEncrypter(block, iv)
```

**Comment by emmansun** [comment]
https://pkg.go.dev/github.com/emmansun/gmsm@v0.29.2/cipher#NewECBEncrypte.

**Comment by ninjachen** [comment]
> 当PKCS5Padding用于block size = 16字节时，其实现和PKCS7Padding结果通常一样

我发现当block size=16时 PKCS5Padding和PKCS7Padding是不一样的，用[这个老哥的补丁](https://blog.csdn.net/qq_42939898/article/details/139601109)，现在我能解密合作方用Java生成的秘文了

**Comment by ninjachen** [comment]
谢谢，不好意思打扰了

**Comment by emmansun** [comment]
> > 当PKCS5Padding用于block size = 16字节时，其实现和PKCS7Padding结果通常一样
> 
> 我发现当block size=16时 PKCS5Padding和PKCS7Padding是不一样的，用[这个老哥的补丁](https://blog.csdn.net/qq_42939898/article/details/139601109)，现在我能解密合作方用Java生成的秘文了

不明白你所说的不一样是指什么。况且你引用代码的Unpadding方法是不安全的。

**Comment by ninjachen** [comment]
合作方用SM4/ECB/PKCS5Padding加密数据，我这边解密。 我试用了
1. https://pkg.go.dev/github.com/emmansun/gmsm@v0.29.2/cipher#NewECBEncrypter. 这里的SM4/ECB/PKCS7Padding
2. github.com/tjfoc/gmsm +  [这个老哥的补丁](https://blog.csdn.net/qq_42939898/article/details/139601109)

方式1和方式2的解密内容是不一样的，我猜是PKCS5Padding和PKCS7Padding是不一样的。方式2的解密内容是我要的

**Comment by emmansun** [comment]
> 合作方用SM4/ECB/PKCS5Padding加密数据，我这边解密。 我试用了
> 
> 1. https://pkg.go.dev/github.com/emmansun/gmsm@v0.29.2/cipher#NewECBEncrypter. 这里的SM4/ECB/PKCS7Padding
> 2. github.com/tjfoc/gmsm +  [这个老哥的补丁](https://blog.csdn.net/qq_42939898/article/details/139601109)
> 
> 方式1和方式2的解密内容是不一样的，我猜是PKCS5Padding和PKCS7Padding是不一样的。方式2的解密内容是我要的

你用Encrypter解密？https://pkg.go.dev/github.com/emmansun/gmsm/cipher#NewECBDecrypter
