### ISSUE TITLE
TLS support.

### ISSUE THREAD

**Issue by shove70** [emmansun/gmsm#59]
Will TLS modules be added? And support TLS 1.3.

**Comment by emmansun** [comment]
tls请参考https://github.com/easyops-cn/ntls-go

**Comment by shove70** [comment]
TKS

**Comment by xuyang2** [comment]
@shove70 也可以关注一下 https://github.com/BabaSSL/BabaSSL/issues/243
BabaSSL 后面可能会出 CGO 的 TLS 包

**Comment by emmansun** [comment]
考虑到开发和维护成本，这个开源项目目前不会去支持国密TLS，而是会聚焦算法本身。

**Comment by shove70** [comment]
> 考虑到开发和维护成本，这个开源项目目前不会去支持国密TLS，而是会聚焦算法本身。

TKS
