### ISSUE TITLE
sm9/bn256.fromBigInt 初始化报错

### ISSUE THREAD

**Issue by xin-1998** [emmansun/gmsm#64]
你好！sm9/bn256.fromBigInt 初始化报错，希望可以有个解决方法
报错信息：
panic: runtime error: index out of range [4] with length 4
goroutine 1 [running]:
github.com/emmansun/gmsm/sm9/bn256.fromBigInt(0x887b20)
        /root/go/pkg/mod/github.com/emmansun/gmsm@v0.13.3/sm9/bn256/gfp.go:40 +0x2a4
github.com/emmansun/gmsm/sm9/bn256.init()
        /root/go/pkg/mod/github.com/emmansun/gmsm@v0.13.3/sm9/bn256/constants.go:57 +0x388

我现在用的运行程序开发板ARM版本，系统为uboot20.04，内核为4.9.88，
编写程序为wsl-20.04，go版本为go version go1.18.2 linux/amd64

**Comment by emmansun** [comment]
你的ARM是32位吗？

**Comment by xin-1998** [comment]
是32位
开发板arm查为armv7l

**Comment by emmansun** [comment]
Released in v0.13.4

**Comment by xin-1998** [comment]
谢谢，问题以解决！！
