### ISSUE TITLE
gmsm库支持对基于1.2.156.10197.1.301 sm2-1数字签名算法的公钥或证书，进行读取和验签操作吗

### ISSUE THREAD

**Issue by zhanghouxin07** [emmansun/gmsm#66]
hi，勤劳的开发者们，

请问gmsm库支持对基于1.2.156.10197.1.301 sm2-1数字签名算法的公钥或证书，进行读取和验签操作吗

我获取了一份国密证书，但在加载证书时报错msg为：x509: not sm2 elliptic curve

代码片段为：
pubKey, err := x509.ReadPublicKeyFromPem(content) // 读取公钥
if err != nil || pubKey == nil {
fmt.Println("failed to read cert file, error is", err)
return
}

请问这个功能可用吗，是否有现有可用的函数可以使用，感谢。

best wishes

**Comment by emmansun** [comment]
```golang
func Test_ParseCertificate(t *testing.T) {
	cert, err := ParseCertificatePEM([]byte(sm2Certificate))
	if err != nil {
		t.Fatal(err)
	}
	_, err = json.Marshal(cert)
	if err != nil {
		t.Fatal(err)
	}
}
```
你可以参考这个测试。

**Comment by emmansun** [comment]
看来你使用的是https://github.com/tjfoc/gmsm ， 不是本项目。

**Comment by zhanghouxin07** [comment]
> 看来你使用的是https://github.com/tjfoc/gmsm ， 不是本项目。

因为https://github.com/tjfoc/gmsm 似乎不支持我需要的能力，因此在尝试找其他解决方案，我先按照您的提供的函数去尝试一下，感谢。

**Comment by emmansun** [comment]
我先关掉这个issue，如果使用本项目时遇到问题，可以提新issue。
