### ISSUE TITLE
关于LoongArch支持

### ISSUE THREAD

**Issue by Trisia** [emmansun/gmsm#71]
作者您好：

我在golang 1.19版本发布说明中发现，在1.19版本下支持了 龙芯 的  LoongArch 64-bit  指令集。

请问作者您后续是否考虑基于 `LoongArch 64-bit`  指令集 进行算法性能优化

- [see Golang release note 1.19](https://github.com/golang/go/blob/master/doc/go1.19.html)

**Comment by emmansun** [comment]
这个......，普及度不够，没有开发测试和CI环境，太难搞。
