### ISSUE TITLE
关于 软件随机数

### ISSUE THREAD

**Issue by Trisia** [emmansun/gmsm#84]
随机数的随机性是密码安全的基础。

在2021-10-19 发布了 [《GMT 0105-2021 软件随机数发生器设计指南》](https://hbba.sacinfo.org.cn/attachment/onlineRead/a302cf337eb6259967e0acc1878ece87b6a32ebe36c3878792a738e7e5c7a5e0)

请问作者是否有兴趣实现该标准中提及的随机源发生器？

标准您可以参考：

- [《GMT 0105-2021 软件随机数发生器设计指南》](https://hbba.sacinfo.org.cn/attachment/onlineRead/a302cf337eb6259967e0acc1878ece87b6a32ebe36c3878792a738e7e5c7a5e0)

**Comment by emmansun** [comment]
好，学习下https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-90Ar1.pdf 先。

**Comment by Trisia** [comment]
好的，感谢！

**Comment by emmansun** [comment]
先实现了HASH DRBG，GM的没有测试数据。看看上层应用怎么使用，是否需要自动reseed等。

https://www.openssl.org/docs/man1.1.1/man7/RAND_DRBG.html

**Comment by Trisia** [comment]
好的，我的需要详细了解下技术细节看看如何集成。

顺带一提，不过是否可以将其抽象成 `io.Reader` 接口，类似于 `crypto/rand/rand.go`

**Comment by emmansun** [comment]
"顺带一提，是否可以将其抽象成 io.Reader 接口，类似于 crypto/rand/rand.go",  这个就是上层应用了（RAND_DRBG），这里只实现了DRBG，可以考虑用io.Reader作为熵源、熵池抽象，这样就可以实现auto reseed；如果要实现io.Reader来获取生成的字节，要看看如何处理Generate方法的additional input参数，简单处理就是不支持该参数。

**Comment by Trisia** [comment]
明白，请问该特性将与什么版本发布？

**Comment by emmansun** [comment]
> 明白，请问该特性将与什么版本发布？

v0.15.0

**Comment by emmansun** [comment]
从扑克测试就和2021的示例不同了，看不出有什么错误，照理扑克测试没有改变。
![image](https://user-images.githubusercontent.com/7235232/197992426-bf7153d0-b57b-4e13-8528-c9629d04d6a5.png)
