### ISSUE TITLE
sm4的ECB模式有吗

### ISSUE THREAD

**Issue by dzwvip** [emmansun/gmsm#96]
sm4的ECB模式 应该用哪个函数？

**Comment by emmansun** [comment]
你确认要使用ECB模式吗？这种模式非常简单，自己将明文分组直接加密（通过cipher.Block）就是了。

**Comment by dzwvip** [comment]
简单封装一下，可以了，谢谢

**Comment by emmansun** [comment]
通常主要使用的是CBC/CGM模式

**Comment by emmansun** [comment]
Support it since [v0.15.7](https://github.com/emmansun/gmsm/releases/tag/v0.15.7)
