### ISSUE TITLE
怎么把java的sm2 密钥 转成 go的密钥格式

### ISSUE THREAD

**Issue by dzwvip** [emmansun/gmsm#97]
现在是Java的 sm2 密钥对，base64格式的字符串，怎么转成go 能用的密钥格式

**Comment by emmansun** [comment]
这要看你的java怎么marshal你的公私钥的，譬如私钥是一个大数的字节还是符合pkcs8格式(ParsePKCS8PrivateKey/MarshalPKCS8PrivateKey)？公钥的话就是椭圆曲线点还是符合RFC 5280(ParsePKIXPublicKey/MarshalPKIXPublicKey)？

**Comment by dzwvip** [comment]
测试私钥就是这个串 VrSN8C9M/YvTTK55eWJ0i257pPCJrc6Lc+kRLIZgxPc=

**Comment by dzwvip** [comment]
应该是一个大数的字节 ，不知道怎么转成 该项目里的 sm2.PrivateKey

**Comment by emmansun** [comment]
这样的话，只能参考GenerateKey方法，自己创建sm2.PrivateKey。最好分享一下java代码。

**Comment by dzwvip** [comment]
这是java使用密钥的代码：
`public String sign(String plainText, String prvKey) throws NoSuchAlgorithmException, InvalidKeySpecException, InvalidKeyException, SignatureException, IOException {
        Signature signature = Signature.getInstance(GMObjectIdentifiers.sm2sign_with_sm3.toString(), this.provider);
        BigInteger bigInteger = new BigInteger(prvKey, 16);
        BCECPrivateKey privateKey = (BCECPrivateKey)this.keyFactory.generatePrivate(new ECPrivateKeySpec(bigInteger, this.ecParameterSpec));
        signature.initSign(privateKey);
        signature.update(plainText.getBytes(StandardCharsets.UTF_8));
        String signStr = Base64.getEncoder().encodeToString(signature.sign());
        signStr = (new BigInteger(this.decoder.decodeBuffer(signStr))).toString(16);
        String derStr = SM2Util.SM2SignAsn1.parseSm2SignAsn1Object(signStr);
        byte[] hexStr = Hex.decode(derStr);
        String signData = Base64.getEncoder().encodeToString(hexStr);
        return signData;
    }

    public boolean verify(String plainText, String signatureValue, String pubKey) throws NoSuchAlgorithmException {
        Signature signature = Signature.getInstance(GMObjectIdentifiers.sm2sign_with_sm3.toString(), this.provider);

        try {
            ECPoint ecPoint = this.parameters.getCurve().decodePoint(Hex.decode(pubKey));
            BCECPublicKey key = (BCECPublicKey)this.keyFactory.generatePublic(new ECPublicKeySpec(ecPoint, this.ecParameterSpec));
            signature.initVerify(key);
            signature.update(plainText.getBytes(StandardCharsets.UTF_8));
            byte[] signDataByte = Base64.getDecoder().decode(signatureValue);
            String sigDataHex = Hex.toHexString(signDataByte);
            List<String> list = CommonUtil.getStrList(sigDataHex, 64, 2);
            String sm2SignAsn1 = SM2Util.SM2SignAsn1.buildSm2SignAsn1Object(new BigInteger((String)list.get(0), 16), new BigInteger((String)list.get(1), 16));
            byte[] sm2SignAsn1Byte = Hex.decode(sm2SignAsn1);
            String sm2SignAsn1ByteText = Base64.getEncoder().encodeToString(sm2SignAsn1Byte);
            return signature.verify(Base64.getDecoder().decode(sm2SignAsn1ByteText));
        } catch (Exception var13) {
            return false;
        }
    }`

**Comment by emmansun** [comment]
看这代码确实是hex格式的数字字符串

**Comment by dzwvip** [comment]
我看 GenerateKey 方法里用的 p256() 是未导出的，如果用指定的 大数字节 应该怎样生成 PrivateKey 呢？ 有示例吗

**Comment by emmansun** [comment]
可以用sm2.P256()，你只要能生成big.Int就行。

**Comment by dzwvip** [comment]
刚才试着写了一下，能签名 但是用别的工具验签失败 ，，GenerateKey 里的 randomPoint函数 不知道该怎么改
`func RawBytesToPrivateKey(bytes []byte) (*sm2.PrivateKey, error) {
	privateKey := new(sm2.PrivateKey)
	privateKey.Curve = sm2.P256()
	//k, Q, err := randomPoint(c, rand)
	//if err != nil {
	//	return nil, err
	//}
	privateKey.D = new(big.Int).SetBytes(bytes)
	privateKey.PublicKey.Curve = sm2.P256()
	privateKey.X, privateKey.Y = privateKey.Curve.ScalarBaseMult(privateKey.D.Bytes())
	return privateKey, nil
}
func Sm2SignWithSm3(key []byte, indata string) (string, error) {
	priv, err := RawBytesToPrivateKey(key)
	if err != nil {
		return "", err
	}
	hashed := sm3.Sum([]byte(indata))
	signature, err := priv.Sign(rand.Reader, hashed[:], nil)
	if err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(signature), nil

}`

**Comment by emmansun** [comment]
你自己要知道应该调用Sign()还是SignWithSM2()；签名结果是(r,s)的ASN1格式；需要确认“其它工具”的验签方法的签名输入格式是否一致；最后确认私钥的正确性（通过比较私钥中的公钥和验签方法的公钥）。
